### ISSUE TITLE
mountpoint-assignment-X test failing on daily-iso with "org.fedoraproject.Anaconda.Modules.Storage:AttributeError: 'NoneType' object has no attribute 'device_id'"

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#1273]
Since 2024_08_06
Seems to be caused by https://github.com/rhinstaller/anaconda/pull/5435 which went in lately.
```
3:51:32,757 WARNING org.fedoraproject.Anaconda.Modules.Storage:DEBUG:anaconda.storage:Finished a copy of the storage model.
23:51:32,769 WARNING org.fedoraproject.Anaconda.Modules.Storage:DEBUG:blivet:                 DeviceTree.get_device_by_path: path: /dev/vda1 ; incomplete: False ; hidden: False ;
23:51:32,774 WARNING org.fedoraproject.Anaconda.Modules.Storage:DEBUG:blivet:                 DeviceTree.get_device_by_path returned None
23:51:32,774 WARNING org.fedoraproject.Anaconda.Modules.Storage:DEBUG:blivet:failed to resolve '/dev/vda1'
23:51:32,778 WARNING org.fedoraproject.Anaconda.Modules.Storage:WARNING:dasbus.server.handler:The call org.fedoraproject.Anaconda.Modules.ReadKickstart has failed with an exception:
23:51:32,778 WARNING org.fedoraproject.Anaconda.Modules.Storage:Traceback (most recent call last):
23:51:32,778 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.13/site-packages/dasbus/server/handler.py", line 455, in _method_callback
23:51:32,778 WARNING org.fedoraproject.Anaconda.Modules.Storage:    result = self._handle_call(
23:51:32,778 WARNING org.fedoraproject.Anaconda.Modules.Storage:        interface_name,
23:51:32,778 WARNING org.fedoraproject.Anaconda.Modules.Storage:    ...<2 lines>...
23:51:32,778 WARNING org.fedoraproject.Anaconda.Modules.Storage:        **additional_args
23:51:32,778 WARNING org.fedoraproject.Anaconda.Modules.Storage:    )
23:51:32,778 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.13/site-packages/dasbus/server/handler.py", line 265, in _handle_call
23:51:32,778 WARNING org.fedoraproject.Anaconda.Modules.Storage:    return handler(*parameters, **additional_args)
23:51:32,778 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.13/site-packages/dasbus/server/property.py", line 51, in wrapper
23:51:32,778 WARNING org.fedoraproject.Anaconda.Modules.Storage:    result = method(obj, *args, **kwargs)
23:51:32,778 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.13/site-packages/pyanaconda/modules/common/base/base_interface.py", line 91, in ReadKickstart
23:51:32,778 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self.implementation.read_kickstart(kickstart)
23:51:32,778 WARNING org.fedoraproject.Anaconda.Modules.Storage:    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
23:51:32,778 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.13/site-packages/pyanaconda/modules/common/base/base.py", line 233, in read_kickstart
23:51:32,778 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self.process_kickstart(handler)
23:51:32,778 WARNING org.fedoraproject.Anaconda.Modules.Storage:    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
23:51:32,778 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.13/site-packages/pyanaconda/modules/storage/storage.py", line 158, in process_kickstart
23:51:32,778 WARNING org.fedoraproject.Anaconda.Modules.Storage:    partitioning_module.process_kickstart(data)
23:51:32,778 WARNING org.fedoraproject.Anaconda.Modules.Storage:    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
23:51:32,778 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.13/site-packages/pyanaconda/modules/storage/partitioning/manual/manual_module.py", line 62, in process_kickstart
23:51:32,778 WARNING org.fedoraproject.Anaconda.Modules.Storage:    request.device_spec = device.device_id
23:51:32,778 WARNING org.fedoraproject.Anaconda.Modules.Storage:                          ^^^^^^^^^^^^^^^^
23:51:32,778 WARNING org.fedoraproject.Anaconda.Modules.Storage:AttributeError: 'NoneType' object has no attribute 'device_id'
23:51:32,792 WARNING org.fedoraproject.Anaconda.Boss:WARNING:dasbus.server.handler:The call org.fedoraproject.Anaconda.Boss.ReadKickstartFile has failed with an exception:
23:51:32,792 WARNING org.fedoraproject.Anaconda.Boss:Traceback (most recent call last):
23:51:32,792 WARNING org.fedoraproject.Anaconda.Boss:  File "/usr/lib/python3.13/site-packages/dasbus/server/handler.py", line 455, in _method_callback
23:51:32,792 WARNING org.fedoraproject.Anaconda.Boss:    result = self._handle_call(
23:51:32,792 WARNING org.fedoraproject.Anaconda.Boss:        interface_name,
23:51:32,792 WARNING org.fedoraproject.Anaconda.Boss:    ...<2 lines>...
23:51:32,792 WARNING org.fedoraproject.Anaconda.Boss:        **additional_args
23:51:32,792 WARNING org.fedoraproject.Anaconda.Boss:    )
23:51:32,792 WARNING org.fedoraproject.Anaconda.Boss:  File "/usr/lib/python3.13/site-packages/dasbus/server/handler.py", line 265, in _handle_call
23:51:32,792 WARNING org.fedoraproject.Anaconda.Boss:    return handler(*parameters, **additional_args)
23:51:32,792 WARNING org.fedoraproject.Anaconda.Boss:  File "/usr/lib64/python3.13/site-packages/pyanaconda/modules/boss/boss_interface.py", line 74, in ReadKickstartFile
23:51:32,792 WARNING org.fedoraproject.Anaconda.Boss:    self.implementation.read_kickstart_file(path)
23:51:32,792 WARNING org.fedoraproject.Anaconda.Boss:    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
23:51:32,792 WARNING org.fedoraproject.Anaconda.Boss:  File "/usr/lib64/python3.13/site-packages/pyanaconda/modules/boss/boss.py", line 86, in read_kickstart_file
23:51:32,792 WARNING org.fedoraproject.Anaconda.Boss:    return self._kickstart_manager.read_kickstart_file(path)
23:51:32,792 WARNING org.fedoraproject.Anaconda.Boss:           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
23:51:32,792 WARNING org.fedoraproject.Anaconda.Boss:  File "/usr/lib64/python3.13/site-packages/pyanaconda/modules/boss/kickstart_manager/kickstart_manager.py", line 58, in read_kickstart_file
23:51:32,792 WARNING org.fedoraproject.Anaconda.Boss:    reports = self._distribute_to_modules(elements)
23:51:32,792 WARNING org.fedoraproject.Anaconda.Boss:  File "/usr/lib64/python3.13/site-packages/pyanaconda/modules/boss/kickstart_manager/kickstart_manager.py", line 111, in _distribute_to_modules
23:51:32,792 WARNING org.fedoraproject.Anaconda.Boss:    observer.proxy.ReadKickstart(module_kickstart)
23:51:32,792 WARNING org.fedoraproject.Anaconda.Boss:    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
23:51:32,792 WARNING org.fedoraproject.Anaconda.Boss:  File "/usr/lib/python3.13/site-packages/dasbus/client/handler.py", line 450, in _call_method
23:51:32,792 WARNING org.fedoraproject.Anaconda.Boss:    return self._get_method_reply(
23:51:32,792 WARNING org.fedoraproject.Anaconda.Boss:           ~~~~~~~~~~~~~~~~~~~~~~^
23:51:32,792 WARNING org.fedoraproject.Anaconda.Boss:        self._client.sync_call,
23:51:32,792 WARNING org.fedoraproject.Anaconda.Boss:        ^^^^^^^^^^^^^^^^^^^^^^^
23:51:32,792 WARNING org.fedoraproject.Anaconda.Boss:        *args,
23:51:32,792 WARNING org.fedoraproject.Anaconda.Boss:        ^^^^^^
23:51:32,792 WARNING org.fedoraproject.Anaconda.Boss:        **kwargs,
23:51:32,792 WARNING org.fedoraproject.Anaconda.Boss:        ^^^^^^^^^
23:51:32,792 WARNING org.fedoraproject.Anaconda.Boss:    )
23:51:32,792 WARNING org.fedoraproject.Anaconda.Boss:    ^
23:51:32,792 WARNING org.fedoraproject.Anaconda.Boss:  File "/usr/lib/python3.13/site-packages/dasbus/client/handler.py", line 483, in _get_method_reply
23:51:32,792 WARNING org.fedoraproject.Anaconda.Boss:    return self._handle_method_error(error)
23:51:32,792 WARNING org.fedoraproject.Anaconda.Boss:           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
23:51:32,792 WARNING org.fedoraproject.Anaconda.Boss:  File "/usr/lib/python3.13/site-packages/dasbus/client/handler.py", line 509, in _handle_method_error
23:51:32,792 WARNING org.fedoraproject.Anaconda.Boss:    raise exception from None
23:51:32,792 WARNING org.fedoraproject.Anaconda.Boss:pyanaconda.modules.common.errors.general.AnacondaError: 'NoneType' object has no attribute 'device_id'
```
mountpoint-assignment-1:
[kstest.log](https://github.com/user-attachments/files/16521609/kstest.log)
[virt-install.log](https://github.com/user-attachments/files/16521611/virt-install.log)
mountpoint-assignment-2:
[kstest.log](https://github.com/user-attachments/files/16521613/kstest.log)
[virt-install.log](https://github.com/user-attachments/files/16521614/virt-install.log)
